# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: codenplay
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  environment:
    BUCKET_NAME: category-images-neela-dev-bucket
    REGION: ap-southeast-2
    DYNAMODB_TABLE: Categories
    SNS_TOPIC_ARN: arn:aws:sns:ap-southeast-2:017341176574:category-cleanup-topic
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::category-images-neela-dev-bucket/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:ap-southeast-2:017341176574:table/Categories"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "arn:aws:sns:ap-southeast-2:017341176574:category-cleanup-topic"

      
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

resources:
  Resources:
    CategoryImagesBucket:   # This is the S3 bucket that will be used to store the category images
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-images-neela-dev-bucket # it need to be unique across all AWS accounts and regions
      DeletionPolicy: Retain # This will prevent the bucket from being deleted when you remove the service. Remove this line if you want the bucket to be deleted.
    CategoryTable:    # This is the DynamoDB table that will be used to store the category data
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CategoryCleanupTopic:      # This is the SNS topic that will be used to trigger the cleanupCategories function
      Type: AWS::SNS::Topic
      Properties:
        TopicName: category-cleanup-topic
    CategoryCleanupSubscription:   # This is the subscription that will trigger the cleanupCategories function when a message is published to the SNS topic
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:ap-southeast-2:017341176574:category-cleanup-topic  #!Ref CategoryCleanupTopic
        Protocol: email
        Endpoint: kkfneela@hotmail.com # Change this to your email address to receive notifications when the cleanupCategories function is triggered

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
  updateCategoryImage:
    handler: handlers/updateCategoryImage.updateCategoryImage
    events:
      - s3:
          bucket: category-images-neela-dev-bucket
          event: s3:ObjectCreated:Put
          existing: true
  cleanupCategories:
    handler: handlers/cleanupCategories.cleanupCategories
    events:
      - schedule:
          rate: rate(2 minutes)
